### ISSUE TITLE
Invisible pager controls in Form Wizard Pro "Browse Submissions"

### ISSUE THREAD

**Issue by CrispinF** [exeGesIS-SDM/esdm-mojowebsite-skin#2]
Example:
![image](https://user-images.githubusercontent.com/10574730/43186900-00560178-8fe8-11e8-87f2-f9ca02f53b98.png)
the Next and Last controls are not visible.
To find an example, https://www.esdm.co.uk/training see the form on the left, go to Administration, then Submission Data, then Browse Submissions

**Comment by hefin1** [comment]
Caused by fontawesome font not being loaded .

The browse submissions is an iFrame to the FormWizard

`<iframe frameborder="0" name="1534346377966" allowfullscreen="" src="https://www.esdm.co.uk/FormWizard/FormResultsBrowse.aspx?mid= 599&amp;pageid=40" class="cboxIframe"></iframe>`

It's got the ESDM skin attached, but we're probably loading the fontawesome in the Layout page. I'll check out what's happening.

**Comment by hefin1** [comment]
Issue can be seen in the mojoportal demo site setup by i7 Media in their form wizard pro pop-up as well. Bug report raised.

[https://www.mojoportal.com/Forums/Thread.aspx?pageid=5&t=13879~1#post55892](https://www.mojoportal.com/Forums/Thread.aspx?pageid=5&t=13879~1#post55892)

**Comment by hefin1** [comment]
As a workaround I've added a reference to the font awesome from the a CDN in the .aspx files

- D:\Websites\mojoPortal_ESDM\FormWizard\FormResultsGrid.aspx
- D:\Websites\mojoPortal_ESDM\FormWizard\FormResultsBrowse.aspx

`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" crossorigin="anonymous">`

**Comment by hefin1** [comment]
Over to @CrispinF to test and sign off.

**Comment by CrispinF** [comment]
Fine
